# Generated by Django 3.1.1 on 2020-11-07 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_auto_20201107_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
