# Generated by Django 3.1.1 on 2020-11-07 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_auto_20201107_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
