# Generated by Django 3.1.1 on 2020-11-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20201107_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdetails',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
