# Generated by Django 3.1.1 on 2020-11-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_patientdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='Date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
